name: sklearn
channels:
  - conda-forge
  - anaconda-fusion
  - defaults
dependencies:
  - notebook=6.0.1
  - jupyterlab = 3.1.13
  - plotly = 5.3.1
  - pandas=1.3.0
  - scikit-learn=0.24.2
  - jupytext=1.12.0 
  - matplotlib=3.4.3

